# Dev purpose only. DO NOT use in production.
name: spring-authorization-server-samples
services:
  app:
    image: docker.io/suayb/spring-authorization-server-samples:latest-native
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/authserversamples
      - SPRING_DATASOURCE_USERNAME=appuser
      - SPRING_LIQUIBASE_ENABLED=false
      - APP_AUTHORIZATION_SERVER_ISSUER=http://127.0.0.1:9090
      - APP_AUTHORIZATION_SERVER_JWK_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvpR5qeCNqweWqX/Baqr5cXNuGe1dBYnr0aME4c6NrQa4Qp4Gh/V49kKUMSQK0AqwpH8nv+lCrO6JqWqTg3VlsPONitCFb2OrJOpFV8qyDPzbY0krZ8p6b/TywNS7kg2Kpd6hQld+rDFn8nHgLjvkscYCwLnMa9ZRjjTAvN9thJ4oRt9c4uFC8f3cQ+inOK8VJ8m++uD+R5CqF1TTvly8ugqlTNUo3IeZQfF1UOd16Tz8OgNrQfc/Hg4sRQNUGawDEIgEG09zdtsfcdQd8okfRXxtRKbmoymkjwRviNxgpH+POvI9OtqKjbtedj33mLNvGdQ4sgBsmnnjPB9FuMsljwIDAQAB
      - APP_AUTHORIZATION_SERVER_JWK_PRIVATE_KEY=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC+lHmp4I2rB5apf8Fqqvlxc24Z7V0FievRowThzo2tBrhCngaH9Xj2QpQxJArQCrCkfye/6UKs7ompapODdWWw842K0IVvY6sk6kVXyrIM/NtjSStnynpv9PLA1LuSDYql3qFCV36sMWfyceAuO+SxxgLAucxr1lGONMC8322EnihG31zi4ULx/dxD6Kc4rxUnyb764P5HkKoXVNO+XLy6CqVM1Sjch5lB8XVQ53XpPPw6A2tB9z8eDixFA1QZrAMQiAQbT3N22x9x1B3yiR9FfG1EpuajKaSPBG+I3GCkf4868j062oqNu152PfeYs28Z1DiyAGyaeeM8H0W4yyWPAgMBAAECggEAEFdj3USjcSRb71nEiHRzoh4/NRrszIJIhbfAPep7rHf0icXKEpNiVV9dHJ+WC8O25MwAaQzDyldD15KLZozE9PjVTK9XmbcGoEo0OvRm8wUlfKxz+9jZSctLm2xCTyI5HsLpueoNsw8jdh78lYpOME4lw0fLNv3wDU0Jr8hKuEG/aZc6xDfEKFFrs7LnVFasPL8kEQ2K0HHHI2s4eYhJGJcubuRMDy8Pnk/Jezmfs78DAJFosny6tWFFQ4xmPoTLq9PErnY/sY+dlpBC2FjO+muex7tKU865Qt9bEieEYD3zXFS3Qv/G7bZmzUnBByM0wMMLabAPiOalJrUTHNT9zQKBgQD0IFsUKEWt/R2iVkGy8hjj+E1oXXJbfQMnPv8caYf/cth0kABJppFsiHzG379yKdi7BGf4866HDdI4srgrT4hNHYddcLZ7fEnSpDMocvmnivE+YNDEFyhhgLJwzcCvJkAPHPWQFkbQaBNMtEpXEdFup+Q0+pBF+eRiPe/Pmhvf9QKBgQDH2WhGHKRbZKSjea94yT1956ZlDBrL+WE6LMGBc0XqomibBAByuIqaohzh37E7STAPNVxW//osEN93iBq+PRjtnNY3LmSp57GGGqW/GZO8MDtznhCUhc6Z1cfIIclfdVmNubctTc2b4Db0Oppv/gXhvfTV4IH5zWE59KGWJlVQ8wKBgAp5iO7oe3Tns2nPwann8WF2ufuMZue+CXCZp2CUtp0jVF5L/3cpinvZr2DpINHJMd90ZPGtowNweGCuanCRTQviBHjh6TKLNq+vE/LcXBHwSEGg7dQ8GiN03jMw4N+jCISdfXvdONSgYpOb+MSboxzYX1ZWmfImssH0XmHN/vwxAoGBAMYaGGcHlVSTGzCBOxN8SFw5+JNJwHZZKavFGbv8TF4dx5uCB/+wNpS6Be9REho2nlE1D+edrptnzlxqqjfR0JgZU683acmSRkMsvwgDjpKJLSWalczkJrwPUg5sj3T0mmUGpzFdYmcVhuPqA5ToNWRkLAKmnbDFiY8tk8+HCCNJAoGASwNnPmapRhN4Pt4DMIp5BKv7bXKdcxmc9SC95BNXwMBPBHPDMETaoEuHXl3EKA4qXStjaC2yWbAMwGzw/VtYEpHzXZylBb3NDGymlkucvfOvrB7VgXBo4I8wqksRpGiY4Hk5Q/YVw5fJO89wTfuumkoWi0ppn8jDgqyPEnxMa+o=
      - APP_AUTHORIZATION_SERVER_JWK_KEY_ID=7FD1B2BF-4E82-45E9-A93D-8BEF97E1D201
    ports:
      - "127.0.0.1:9090:9090"
    depends_on:
      postgresql:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully

  liquibase:
    image: docker.io/suayb/liquibase-postgresql:5.0.1
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://postgresql:5432/authserversamples
      - LIQUIBASE_COMMAND_USERNAME=appuser
      - LIQUIBASE_COMMAND_CHANGELOG_FILE=db/changelog/db.changelog-master.xml
    volumes:
      - ../resources/db:/liquibase/db:ro
    command:
      - update

  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
