apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-authorization-server-samples.fullname" . }}-secret-jwk
  labels:
    {{ include "spring-authorization-server-samples.labels" . | nindent 4 }}
type: Opaque
data:
  public-key: {{ .Values.app.authorizationServer.jwk.publicKey | b64enc | quote }}
  private-key: {{ .Values.app.authorizationServer.jwk.privateKey | b64enc | quote }}
  key-id: {{ .Values.app.authorizationServer.jwk.keyId | b64enc | quote }}
