# Default values for spring-authorization-server-samples.

replicaCount: 2
terminationGracePeriodSeconds: 30
revisionHistoryLimit: 10

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

image:
  repository: docker.io/suayb/spring-authorization-server-samples
  pullPolicy: IfNotPresent
  tag: "latest-native"

initContainers:
  waitForDb:
    enabled: true
    image:
      repository: busybox
      pullPolicy: IfNotPresent
      tag: "1.37.0"
  liquibase:
    enabled: true
    image:
      repository: docker.io/suayb/liquibase-postgresql
      pullPolicy: IfNotPresent
      tag: "5.0.1"
    changeLogFile: db/changelog/db.changelog-master.xml

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

containerPort: 9090

spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://postgresql:5432/authserversamples
    username: appuser
    password: "V5tDoPwOjIkoFLmO9X3W/l9VnfTVoXYo"
  liquibase:
    enabled: false

authorizationServer:
  issuer: https://spring-authorization-server-samples.local
  jwk:
    publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvpR5qeCNqweWqX/Baqr5cXNuGe1dBYnr0aME4c6NrQa4Qp4Gh/V49kKUMSQK0AqwpH8nv+lCrO6JqWqTg3VlsPONitCFb2OrJOpFV8qyDPzbY0krZ8p6b/TywNS7kg2Kpd6hQld+rDFn8nHgLjvkscYCwLnMa9ZRjjTAvN9thJ4oRt9c4uFC8f3cQ+inOK8VJ8m++uD+R5CqF1TTvly8ugqlTNUo3IeZQfF1UOd16Tz8OgNrQfc/Hg4sRQNUGawDEIgEG09zdtsfcdQd8okfRXxtRKbmoymkjwRviNxgpH+POvI9OtqKjbtedj33mLNvGdQ4sgBsmnnjPB9FuMsljwIDAQAB"
    privateKey: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC+lHmp4I2rB5apf8Fqqvlxc24Z7V0FievRowThzo2tBrhCngaH9Xj2QpQxJArQCrCkfye/6UKs7ompapODdWWw842K0IVvY6sk6kVXyrIM/NtjSStnynpv9PLA1LuSDYql3qFCV36sMWfyceAuO+SxxgLAucxr1lGONMC8322EnihG31zi4ULx/dxD6Kc4rxUnyb764P5HkKoXVNO+XLy6CqVM1Sjch5lB8XVQ53XpPPw6A2tB9z8eDixFA1QZrAMQiAQbT3N22x9x1B3yiR9FfG1EpuajKaSPBG+I3GCkf4868j062oqNu152PfeYs28Z1DiyAGyaeeM8H0W4yyWPAgMBAAECggEAEFdj3USjcSRb71nEiHRzoh4/NRrszIJIhbfAPep7rHf0icXKEpNiVV9dHJ+WC8O25MwAaQzDyldD15KLZozE9PjVTK9XmbcGoEo0OvRm8wUlfKxz+9jZSctLm2xCTyI5HsLpueoNsw8jdh78lYpOME4lw0fLNv3wDU0Jr8hKuEG/aZc6xDfEKFFrs7LnVFasPL8kEQ2K0HHHI2s4eYhJGJcubuRMDy8Pnk/Jezmfs78DAJFosny6tWFFQ4xmPoTLq9PErnY/sY+dlpBC2FjO+muex7tKU865Qt9bEieEYD3zXFS3Qv/G7bZmzUnBByM0wMMLabAPiOalJrUTHNT9zQKBgQD0IFsUKEWt/R2iVkGy8hjj+E1oXXJbfQMnPv8caYf/cth0kABJppFsiHzG379yKdi7BGf4866HDdI4srgrT4hNHYddcLZ7fEnSpDMocvmnivE+YNDEFyhhgLJwzcCvJkAPHPWQFkbQaBNMtEpXEdFup+Q0+pBF+eRiPe/Pmhvf9QKBgQDH2WhGHKRbZKSjea94yT1956ZlDBrL+WE6LMGBc0XqomibBAByuIqaohzh37E7STAPNVxW//osEN93iBq+PRjtnNY3LmSp57GGGqW/GZO8MDtznhCUhc6Z1cfIIclfdVmNubctTc2b4Db0Oppv/gXhvfTV4IH5zWE59KGWJlVQ8wKBgAp5iO7oe3Tns2nPwann8WF2ufuMZue+CXCZp2CUtp0jVF5L/3cpinvZr2DpINHJMd90ZPGtowNweGCuanCRTQviBHjh6TKLNq+vE/LcXBHwSEGg7dQ8GiN03jMw4N+jCISdfXvdONSgYpOb+MSboxzYX1ZWmfImssH0XmHN/vwxAoGBAMYaGGcHlVSTGzCBOxN8SFw5+JNJwHZZKavFGbv8TF4dx5uCB/+wNpS6Be9REho2nlE1D+edrptnzlxqqjfR0JgZU683acmSRkMsvwgDjpKJLSWalczkJrwPUg5sj3T0mmUGpzFdYmcVhuPqA5ToNWRkLAKmnbDFiY8tk8+HCCNJAoGASwNnPmapRhN4Pt4DMIp5BKv7bXKdcxmc9SC95BNXwMBPBHPDMETaoEuHXl3EKA4qXStjaC2yWbAMwGzw/VtYEpHzXZylBb3NDGymlkucvfOvrB7VgXBo4I8wqksRpGiY4Hk5Q/YVw5fJO89wTfuumkoWi0ppn8jDgqyPEnxMa+o="
    keyId: "7FD1B2BF-4E82-45E9-A93D-8BEF97E1D201"

existingSecret:
  enabled: false
  name: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

dnsPolicy: ""
dnsConfig: {}

enableServiceLinks: true

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 9090

probes:
  startup:
    enabled: false
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 10
  liveness:
    enabled: true
    path: /actuator/health/liveness
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readiness:
    enabled: true
    path: /actuator/health/readiness
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

ingress:
  enabled: false
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: spring-authorization-server-samples.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: "500m"
    memory: "256Mi"
  limits:
    cpu: "1"
    memory: "512Mi"

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      selectPolicy: Max
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      selectPolicy: Max
      policies:
        - type: Pods
          value: 1
          periodSeconds: 300

nodeSelector: {}
tolerations: []
affinity: {}

postgresql:
  fullnameOverride: postgresql
  enabled: true
  architecture: standalone
  auth:
    username: appuser
    database: authserversamples
    password: "V5tDoPwOjIkoFLmO9X3W/l9VnfTVoXYo"
    existingSecret: ""
    secretKeys:
      userPasswordKey: password
  primary:
    networkPolicy:
      enabled: false
    persistence:
      enabled: false
      size: 8Gi
  metrics:
    enabled: false
  backup:
    enabled: false
